class Stedi < Formula
  desc "Agent-friendly CLI for the Stedi APIs, driven by the official OpenAPI specs"
  homepage "https://github.com/useTaiga/stedi-cli"
  version "0.2.0"
  license "MIT"

  # This formula is rewritten automatically by the release workflow with the
  # real version, release URLs, and sha256 checksums on each tagged release.
  on_macos do
    on_arm do
      url "https://github.com/useTaiga/stedi-cli/releases/download/v0.2.0/stedi-aarch64-apple-darwin.tar.gz"
      sha256 "e6ad10247562074650ba4f06672d389f6b121d0b2d667870484c151e11a86317"
    end
    on_intel do
      url "https://github.com/useTaiga/stedi-cli/releases/download/v0.2.0/stedi-x86_64-apple-darwin.tar.gz"
      sha256 "ebb0509b50d9810791c9290990b99b6790efdf7ec6e2a3f1521bcb1a11b23574"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/useTaiga/stedi-cli/releases/download/v0.2.0/stedi-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "5640edeae9c40e6a92b78b785d871dac21a1cc53585a73663d5a06e56421ece7"
    end
    on_intel do
      url "https://github.com/useTaiga/stedi-cli/releases/download/v0.2.0/stedi-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "81e75a6e47a3df5a8b87fb32672066b0de12aacdc5c4a7812fc98fc5593d3dbf"
    end
  end

  def install
    bin.install "stedi"
    # Ship shell completions and a man page generated by the binary itself.
    generate_completions_from_executable(bin/"stedi", "completions")
    man_dir = buildpath/"man"
    system bin/"stedi", "man", "--dir", man_dir
    man1.install Dir[man_dir/"*.1"]
  end

  test do
    assert_match "stedi", shell_output("#{bin}/stedi --version")
  end
end
